// src/app/api/admin/showcase/route.ts
import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { getCollection } from '@/lib/mongodb';
import { ObjectId } from 'mongodb';

const SHOWCASE_TAG = '__showcase__';

function future(days: number) {
  return new Date(Date.now() + days * 24 * 60 * 60 * 1000);
}

const SHOWCASE_CAMPS = [
  {
    name: 'Web Development Bootcamp',
    category: 'Programming',
    tags: ['frontend', 'web', 'javascript', 'react', SHOWCASE_TAG],
    date: '15-17 มีนาคม 2568',
    location: 'อาคารศูนย์นวัตกรรมและเทคโนโลยี มหาวิทยาลัยเกษตรศาสตร์ บางเขน กรุงเทพฯ',
    price: '฿500',
    image: 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=800&q=80',
    description: 'ค่าย Web Development Bootcamp พาคุณเข้าสู่โลกของการพัฒนาเว็บไซต์ตั้งแต่ระดับพื้นฐานจนถึงระดับกลาง ครอบคลุมทั้ง HTML5, CSS3, JavaScript ES6+ และ React ผ่านการลงมือทำโปรเจกต์จริงที่ออกแบบมาให้ใกล้เคียงกับการทำงานในบริษัทไอที ผู้เข้าร่วมจะได้เรียนรู้ Responsive Design, Component-based Architecture และ API Integration พร้อมรับ Certificate หลังจบค่าย',
    deadline: '10 มีนาคม 2568',
    registrationDeadline: future(30),
    participantCount: 40,
    capacity: 40,
    enrolled: 28,
    fee: 500,
    activityFormat: 'Workshop',
    qualifications: { level: 'มัธยมปลาย', fields: ['วิทยาศาสตร์', 'คณิตศาสตร์'] },
    additionalInfo: ['นำโน้ตบุ๊คมาเอง', 'มีอาหารกลางวันให้ทุกวัน', 'ฟรี Wi-Fi ความเร็วสูง'],
    galleryImages: [
      'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&q=80',
      'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80',
      'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&q=80',
    ],
    reviews: [
      { id: 'r1', author: 'สมชาย ใจดี', rating: 5, comment: 'ค่ายนี้สอนดีมากครับ วิทยากรอธิบายชัดเจน ได้ความรู้เยอะมากเลย ชอบที่มีโปรเจกต์ให้ทำจริง ทำให้เข้าใจมากกว่าแค่ดูสไลด์', date: '2025-01-15' },
      { id: 'r2', author: 'มินตรา สุขใจ', rating: 4, comment: 'สนุกมากค่ะ ได้ทำโปรเจกต์จริง แต่อยากให้เวลาเรียนมากกว่านี้ เนื้อหาแน่นมากจนต้องทบทวนเองเพิ่ม', date: '2025-01-16' },
      { id: 'r3', author: 'ธนภัทร รักเรียน', rating: 5, comment: 'เนื้อหาแน่นมาก ได้ทักษะที่ใช้งานได้จริง แนะนำเลยครับ โดยเฉพาะคนที่อยากเริ่มต้นสาย Web Dev', date: '2025-01-17' },
      { id: 'r4', author: 'วรรณา พัฒนาตน', rating: 5, comment: 'ประทับใจมากค่ะ พี่เลี้ยงช่วยเหลือดีมาก บรรยากาศการเรียนสนุกไม่น่าเบื่อเลย', date: '2025-01-18' },
    ],
    avgRating: 4.8,
    ratingBreakdown: { '5': 3, '4': 1 },
    organizerName: 'KBTG Academy',
    organizerEmail: 'academy@kbtg.tech',
    requiresPortfolio: false,
    featured: true,
    views: 240,
    slug: 'web-dev-bootcamp-showcase',
    organizers: [],
  },
  {
    name: 'Data Science & AI Workshop',
    category: 'Data Science',
    tags: ['data', 'ai', 'machine-learning', 'python', SHOWCASE_TAG],
    date: '22-23 มีนาคม 2568',
    location: 'คณะวิศวกรรมศาสตร์ จุฬาลงกรณ์มหาวิทยาลัย ปทุมวัน กรุงเทพฯ',
    price: '฿800',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
    description: 'สำรวจโลกของ Data Science และ Artificial Intelligence ด้วย Python, Pandas, NumPy และ Scikit-learn เรียนรู้กระบวนการวิเคราะห์ข้อมูลตั้งแต่การทำความสะอาดข้อมูล (Data Cleaning) การสร้าง Visualization ด้วย Matplotlib และ Seaborn ไปจนถึงการสร้างโมเดล Machine Learning เบื้องต้น พร้อม Workshop วิเคราะห์ Dataset จริงจากอุตสาหกรรม เหมาะสำหรับผู้ที่สนใจสายงาน Data Analyst และ Data Scientist',
    deadline: '18 มีนาคม 2568',
    registrationDeadline: future(35),
    participantCount: 30,
    capacity: 30,
    enrolled: 21,
    fee: 800,
    activityFormat: 'Workshop',
    qualifications: { level: 'มัธยมปลาย', fields: ['วิทยาศาสตร์', 'คณิตศาสตร์'] },
    additionalInfo: ['นำโน้ตบุ๊คมาเอง', 'ติดตั้ง Python 3.10+ ก่อนมา', 'มีอาหารว่างและเครื่องดื่มให้'],
    galleryImages: [
      'https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=800&q=80',
      'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=800&q=80',
      'https://images.unsplash.com/photo-1543286386-713bdd548da4?w=800&q=80',
    ],
    reviews: [
      { id: 'r5', author: 'กานต์ดา หวังดี', rating: 5, comment: 'เปิดโลก AI มากเลยค่ะ ไม่เคยรู้มาก่อนว่า Machine Learning น่าสนุกขนาดนี้ วิทยากรอธิบายเข้าใจง่ายมาก', date: '2025-02-01' },
      { id: 'r6', author: 'ปิยะ ฉลาดเรียน', rating: 4, comment: 'เนื้อหาดีมากครับ แต่ค่อนข้างเร็ว ต้องทบทวนเองเพิ่ม อยากให้มีระยะเวลาเรียน 3 วัน', date: '2025-02-02' },
      { id: 'r7', author: 'ณัฐวุฒิ ข้อมูล', rating: 5, comment: 'ได้ทำโปรเจกต์วิเคราะห์ข้อมูลจริงๆ ภูมิใจมากครับ เอาไปใส่ Portfolio ได้เลย', date: '2025-02-03' },
    ],
    avgRating: 4.7,
    ratingBreakdown: { '5': 2, '4': 1 },
    organizerName: 'VISAI.ai',
    organizerEmail: 'academy@visai.ai',
    requiresPortfolio: false,
    featured: true,
    views: 198,
    slug: 'data-science-ai-showcase',
    organizers: [],
  },
  {
    name: 'Cybersecurity Essentials',
    category: 'Security',
    tags: ['cybersecurity', 'network', 'ethical-hacking', 'security', SHOWCASE_TAG],
    date: '5-6 เมษายน 2568',
    location: 'ศูนย์ Cyber Security Excellence Center มหาวิทยาลัยมหิดล ศาลายา นครปฐม',
    price: '฿600',
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80',
    description: 'เรียนรู้ความปลอดภัยทางไซเบอร์เบื้องต้นที่จำเป็นสำหรับโลกดิจิทัล ครอบคลุม Network Security, Penetration Testing เบื้องต้น, การตรวจจับ Vulnerability ด้วย Kali Linux และเครื่องมือ Open Source ยอดนิยม รวมถึง Social Engineering Awareness และ OWASP Top 10 ผู้เข้าร่วมจะได้ฝึกใน Lab Environment จำลองการโจมตีและป้องกันระบบในสภาพแวดล้อมที่ปลอดภัยและถูกกฎหมาย เหมาะสำหรับผู้ที่สนใจสาย Security Engineer',
    deadline: '1 เมษายน 2568',
    registrationDeadline: future(40),
    participantCount: 25,
    capacity: 25,
    enrolled: 18,
    fee: 600,
    activityFormat: 'Workshop',
    qualifications: { level: 'มัธยมปลาย', fields: ['วิทยาศาสตร์'] },
    additionalInfo: ['นำโน้ตบุ๊คมาเอง (RAM 8GB+)', 'ห้ามนำความรู้ไปใช้ผิดกฎหมายโดยเด็ดขาด', 'มี Certificate หลังจบค่าย'],
    galleryImages: [
      'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
      'https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=800&q=80',
    ],
    reviews: [
      { id: 'r8', author: 'ภูมิ ปลอดภัย', rating: 5, comment: 'ได้รู้เรื่อง Ethical Hacking ที่ถูกต้องเลยครับ วิทยากรเก่งและมีประสบการณ์จริงจากงาน Security', date: '2025-02-10' },
      { id: 'r9', author: 'แนน รักษาความปลอดภัย', rating: 5, comment: 'น่าสนใจมากค่ะ อยากเรียนต่อในด้านนี้เลย Lab ออกแบบมาดีมาก', date: '2025-02-11' },
      { id: 'r10', author: 'กิตติ เทคโนโลยี', rating: 4, comment: 'ดีมากครับ เนื้อหาทันสมัย แต่อยากให้มีเวลาทำ CTF เพิ่มอีกนิด', date: '2025-02-12' },
      { id: 'r11', author: 'พลอย ดิจิทัล', rating: 5, comment: 'เปิดตาเรื่องภัยไซเบอร์มากค่ะ กลับไปปรับ Password ใหม่หมดเลย ขอบคุณวิทยากรมากๆ', date: '2025-02-13' },
    ],
    avgRating: 4.8,
    ratingBreakdown: { '5': 3, '4': 1 },
    organizerName: 'ETDA สำนักงานพัฒนาธุรกรรมทางอิเล็กทรอนิกส์',
    organizerEmail: 'training@etda.or.th',
    requiresPortfolio: false,
    featured: false,
    views: 175,
    slug: 'cybersecurity-essentials-showcase',
    organizers: [],
  },
  {
    name: 'Mobile App Development',
    category: 'Programming',
    tags: ['mobile', 'flutter', 'dart', 'app-development', SHOWCASE_TAG],
    date: '19-21 เมษายน 2568',
    location: 'Innovation Hub ชั้น 4 อาคาร True Digital Park สุขุมวิท กรุงเทพฯ',
    price: '฿700',
    image: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&q=80',
    description: 'พัฒนาแอปพลิเคชันมือถือข้ามแพลตฟอร์ม (iOS & Android) ด้วย Flutter Framework และภาษา Dart ตั้งแต่การออกแบบ UI ด้วย Material Design 3, State Management ด้วย Provider/Riverpod, การเชื่อมต่อ REST API, Firebase Authentication และ Firestore Database ไปจนถึงการ Build และ Deploy บน Play Store เนื้อหาออกแบบให้ผู้เรียนสร้างแอปได้จริงภายใน 3 วัน เหมาะสำหรับผู้ที่ต้องการเข้าสู่สายงาน Mobile Developer',
    deadline: '15 เมษายน 2568',
    registrationDeadline: future(45),
    participantCount: 35,
    capacity: 35,
    enrolled: 30,
    fee: 700,
    activityFormat: 'Hackathon',
    qualifications: { level: 'มัธยมปลาย', fields: ['วิทยาศาสตร์', 'คณิตศาสตร์'] },
    additionalInfo: ['นำโน้ตบุ๊คมาเอง', 'ติดตั้ง Flutter SDK และ Android Studio ก่อนมา', 'มีอาหารกลางวันและอาหารว่างให้'],
    galleryImages: [
      'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800&q=80',
      'https://images.unsplash.com/photo-1596558450268-9c27524ba856?w=800&q=80',
      'https://images.unsplash.com/photo-1523206489230-c012c64b2b48?w=800&q=80',
    ],
    reviews: [
      { id: 'r12', author: 'พิมพ์ชนก สร้างแอป', rating: 5, comment: 'ทำแอปได้จริงใน 3 วันค่ะ ภูมิใจมาก แอปที่ทำยังใช้งานอยู่เลย วิทยากรสอนเข้าใจง่ายมาก', date: '2025-03-01' },
      { id: 'r13', author: 'ต้น นักพัฒนา', rating: 4, comment: 'สนุกมากครับ ได้แอปจริงกลับบ้านด้วย แต่อยากให้มีสอน backend เพิ่มสักนิด', date: '2025-03-02' },
      { id: 'r14', author: 'แสงดาว โมบาย', rating: 5, comment: 'ประทับใจมากค่ะ เรียนจบแล้วสมัครงาน Junior Developer ได้เลย', date: '2025-03-03' },
    ],
    avgRating: 4.7,
    ratingBreakdown: { '5': 2, '4': 1 },
    organizerName: 'True Digital Academy',
    organizerEmail: 'academy@truedigital.com',
    requiresPortfolio: false,
    featured: true,
    views: 220,
    slug: 'mobile-app-dev-showcase',
    organizers: [],
  },
  {
    name: 'Game Development with Unity',
    category: 'Game Development',
    tags: ['game', 'unity', 'csharp', '3d', SHOWCASE_TAG],
    date: '3-4 พฤษภาคม 2568',
    location: 'Creative Studio คณะเทคโนโลยีสารสนเทศ มหาวิทยาลัยรังสิต เมืองปทุมธานี',
    price: '฿900',
    image: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=800&q=80',
    description: 'สร้างเกม 2D และ 3D ด้วย Unity Game Engine ภาษา C# ตั้งแต่ Game Design Document, การสร้าง Scene และ GameObject, Physics และ Collision Detection, Animation ด้วย Animator Controller, Game UI ด้วย Canvas System ไปจนถึงการ Export และ Publish เกมบน PC และ WebGL ผู้เข้าร่วมจะได้สร้างเกมสมบูรณ์ 1 เกมที่นำไปแสดงหรือพัฒนาต่อได้ เหมาะสำหรับผู้ที่ฝันอยากทำเกมของตัวเอง',
    deadline: '28 เมษายน 2568',
    registrationDeadline: future(50),
    participantCount: 30,
    capacity: 30,
    enrolled: 22,
    fee: 900,
    activityFormat: 'Workshop',
    qualifications: { level: 'มัธยมปลาย', fields: ['ทุกสาขา'] },
    additionalInfo: ['นำโน้ตบุ๊คมาเอง (RAM 8GB+, GPU)', 'ติดตั้ง Unity 2022 LTS ก่อนมา', 'มีอาหารกลางวันให้'],
    galleryImages: [
      'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=800&q=80',
      'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=800&q=80',
      'https://images.unsplash.com/photo-1560253023-3ec5d502959f?w=800&q=80',
    ],
    reviews: [
      { id: 'r15', author: 'เกม รักเกมส์', rating: 5, comment: 'ฝันมาตลอดว่าจะทำเกมได้ ค่ายนี้ทำให้ฝันนั้นเป็นจริงครับ ได้เกม Platformer ที่เพื่อนเอาไปเล่นจริงๆ', date: '2025-03-15' },
      { id: 'r16', author: 'แพรว ครีเอทีฟ', rating: 5, comment: 'วิทยากรเก่งมากค่ะ อธิบายเข้าใจง่าย มีเกมที่ทำเสร็จสมบูรณ์กลับไปด้วย', date: '2025-03-16' },
      { id: 'r17', author: 'ชนะ เกมมิ่ง', rating: 4, comment: 'สนุกมากครับ แต่อยากให้มีเวลาเพิ่มขึ้นสักวันหนึ่ง เนื้อหาเยอะมาก', date: '2025-03-17' },
      { id: 'r18', author: 'นวพล อินดี้', rating: 5, comment: 'ดีที่สุดเท่าที่เคยเข้าค่ายมา บรรยากาศสนุก ได้ทั้งทักษะและเพื่อนใหม่ที่สนใจเรื่องเดียวกัน', date: '2025-03-18' },
    ],
    avgRating: 4.8,
    ratingBreakdown: { '5': 3, '4': 1 },
    organizerName: 'Game Developer Association Thailand',
    organizerEmail: 'info@gdathai.org',
    requiresPortfolio: false,
    featured: false,
    views: 295,
    slug: 'game-dev-unity-showcase',
    organizers: [],
  },
  {
    name: 'Cloud & DevOps Fundamentals',
    category: 'Infrastructure',
    tags: ['cloud', 'devops', 'docker', 'aws', 'cicd', SHOWCASE_TAG],
    date: '17-18 พฤษภาคม 2568',
    location: 'ห้องปฏิบัติการเครือข่าย คณะวิทยาการคอมพิวเตอร์ มหาวิทยาลัยขอนแก่น',
    price: '฿750',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80',
    description: 'เรียนรู้ Cloud Computing, Container Technology และ DevOps Practices ที่บริษัท IT ชั้นนำทั่วโลกใช้งานจริง ครอบคลุม AWS Core Services (EC2, S3, RDS, Lambda), Docker & Docker Compose, Kubernetes เบื้องต้น, CI/CD Pipeline ด้วย GitHub Actions และ Infrastructure as Code ด้วย Terraform พร้อม Hands-on Lab บน AWS Free Tier เหมาะสำหรับผู้ที่ต้องการเข้าสู่สายงาน DevOps Engineer หรือ Cloud Architect',
    deadline: '12 พฤษภาคม 2568',
    registrationDeadline: future(55),
    participantCount: 25,
    capacity: 25,
    enrolled: 15,
    fee: 750,
    activityFormat: 'Workshop',
    qualifications: { level: 'มัธยมปลาย', fields: ['วิทยาศาสตร์', 'คณิตศาสตร์'] },
    additionalInfo: ['นำโน้ตบุ๊คมาเอง', 'สมัคร AWS Free Tier Account ก่อนมา', 'มี AWS Credit สนับสนุน'],
    galleryImages: [
      'https://images.unsplash.com/photo-1667372393086-9d4001d51cf1?w=800&q=80',
      'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&q=80',
      'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80',
    ],
    reviews: [
      { id: 'r19', author: 'คลาวด์ ดิจิทัล', rating: 5, comment: 'เนื้อหาตรงกับที่ใช้งานจริงในบริษัทเลยครับ ได้ประสบการณ์มากมาย Deploy ได้จริงบน AWS', date: '2025-04-01' },
      { id: 'r20', author: 'นิว เทคโนโลยี', rating: 4, comment: 'ดีมากค่ะ ได้รู้จัก DevOps ที่ไม่เคยรู้มาก่อน อยากให้ AWS credit เพิ่มสักหน่อย', date: '2025-04-02' },
      { id: 'r21', author: 'ดาว Infrastructure', rating: 5, comment: 'CI/CD Pipeline ที่สอนนำไปใช้กับโปรเจกต์ที่ทำงานได้เลยครับ คุ้มมากๆ', date: '2025-04-03' },
    ],
    avgRating: 4.7,
    ratingBreakdown: { '5': 2, '4': 1 },
    organizerName: 'AWS Educate Thailand',
    organizerEmail: 'educate-th@amazon.com',
    requiresPortfolio: false,
    featured: true,
    views: 156,
    slug: 'cloud-devops-showcase',
    organizers: [],
  },
  {
    name: 'UI/UX Design Bootcamp',
    category: 'Design',
    tags: ['ux', 'ui', 'figma', 'design', 'prototype', SHOWCASE_TAG],
    date: '24-25 พฤษภาคม 2568',
    location: 'Creative Space ชั้น 2 สามย่าน มิตรทาวน์ ปทุมวัน กรุงเทพฯ',
    price: '฿650',
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80',
    description: 'ค่าย UI/UX Design ที่ออกแบบมาเพื่อให้ผู้เรียนเข้าใจกระบวนการออกแบบอย่างมีระบบ ตั้งแต่ User Research, Persona Creation, User Journey Mapping, Wireframing, Prototyping ด้วย Figma ไปจนถึง Usability Testing และ Design System เรียนรู้หลักการ Human-Centered Design และ Accessibility เพื่อสร้างผลิตภัณฑ์ที่ผู้ใช้งานรักจริงๆ พร้อม Portfolio ที่สมัครงานได้ทันที',
    deadline: '20 พฤษภาคม 2568',
    registrationDeadline: future(60),
    participantCount: 30,
    capacity: 30,
    enrolled: 24,
    fee: 650,
    activityFormat: 'Workshop',
    qualifications: { level: 'มัธยมปลาย', fields: ['ทุกสาขา'] },
    additionalInfo: ['นำโน้ตบุ๊คมาเอง', 'ติดตั้ง Figma (ฟรี) ก่อนมา', 'ต้องส่ง Portfolio 1 ชิ้นก่อนเข้าร่วม'],
    galleryImages: [
      'https://images.unsplash.com/photo-1586717799252-bd134ad00e26?w=800&q=80',
      'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=800&q=80',
      'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&q=80',
    ],
    reviews: [
      { id: 'r22', author: 'ออมสิน ดีไซน์', rating: 5, comment: 'เปลี่ยนชีวิตเลยค่ะ จากที่ไม่รู้จัก Figma เลย ตอนนี้ทำ Prototype ได้คล่องมาก Portfolio ที่ได้ไปสมัครงานได้จริงๆ', date: '2025-04-10' },
      { id: 'r23', author: 'มาร์ค UX', rating: 4, comment: 'ดีมากครับ สอน Design Thinking อย่างเป็นระบบ อยากให้มีเวลา User Testing เพิ่ม', date: '2025-04-11' },
      { id: 'r24', author: 'ฟ้า Creative', rating: 5, comment: 'วิทยากรมีประสบการณ์ทำงานจริงจากบริษัท Product ที่รู้จักกันดี ได้ความรู้ที่ใช้งานได้จริงมากค่ะ', date: '2025-04-12' },
      { id: 'r25', author: 'เจมส์ Product', rating: 5, comment: 'เข้าใจ User Research มากขึ้นมากครับ ตอนนี้ทำงานร่วมกับ Developer ได้ดีขึ้นมาก', date: '2025-04-13' },
    ],
    avgRating: 4.8,
    ratingBreakdown: { '5': 3, '4': 1 },
    organizerName: 'Design+ Thailand',
    organizerEmail: 'hello@designplus.co.th',
    requiresPortfolio: true,
    featured: true,
    views: 312,
    slug: 'ux-design-bootcamp-showcase',
    organizers: [],
  },
  {
    name: 'Backend Development with Node.js',
    category: 'Programming',
    tags: ['backend', 'nodejs', 'api', 'express', 'database', SHOWCASE_TAG],
    date: '7-8 มิถุนายน 2568',
    location: 'ศูนย์ซอฟต์แวร์แห่งชาติ ถนนเชียงใหม่-ลำพูน จังหวัดเชียงใหม่',
    price: '฿700',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80',
    description: 'เรียนรู้การพัฒนา Backend API ด้วย Node.js และ Express.js ครอบคลุม RESTful API Design, Middleware, Authentication ด้วย JWT, Authorization, การเชื่อมต่อฐานข้อมูลทั้ง MongoDB และ PostgreSQL, Database Transactions, Caching ด้วย Redis, Error Handling, Logging, Unit Testing ด้วย Jest และ API Documentation ด้วย Swagger เหมาะสำหรับผู้ที่อยากเข้าใจการทำงานของ Server Side และต้องการเป็น Full Stack Developer',
    deadline: '3 มิถุนายน 2568',
    registrationDeadline: future(65),
    participantCount: 30,
    capacity: 30,
    enrolled: 20,
    fee: 700,
    activityFormat: 'Workshop',
    qualifications: { level: 'มัธยมปลาย', fields: ['วิทยาศาสตร์', 'คณิตศาสตร์'] },
    additionalInfo: ['นำโน้ตบุ๊คมาเอง', 'มีพื้นฐาน JavaScript เบื้องต้น', 'ติดตั้ง Node.js และ VS Code ก่อนมา'],
    galleryImages: [
      'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=800&q=80',
      'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&q=80',
      'https://images.unsplash.com/photo-1549692520-acc6669e2f0c?w=800&q=80',
    ],
    reviews: [
      { id: 'r26', author: 'แบงค์ Backend', rating: 5, comment: 'เข้าใจ REST API มากขึ้นมากเลยครับ ตอนนี้ทำ Project Full Stack ได้คนเดียวแล้ว', date: '2025-05-01' },
      { id: 'r27', author: 'นิดา เซิร์ฟเวอร์', rating: 5, comment: 'Database design ที่สอนช่วยได้มากค่ะ ไม่เคยเข้าใจ Relationship แบบนี้มาก่อน', date: '2025-05-02' },
      { id: 'r28', author: 'โอ้ต API', rating: 4, comment: 'ดีมากครับ Redis Caching น่าสนใจมาก แต่อยากให้มีเวลาทำ Deploy บน Cloud เพิ่ม', date: '2025-05-03' },
    ],
    avgRating: 4.7,
    ratingBreakdown: { '5': 2, '4': 1 },
    organizerName: 'Wongnai Engineering',
    organizerEmail: 'engineering@wongnai.com',
    requiresPortfolio: false,
    featured: false,
    views: 143,
    slug: 'backend-nodejs-showcase',
    organizers: [],
  },
  {
    name: 'Blockchain & Web3 Workshop',
    category: 'Blockchain',
    tags: ['blockchain', 'web3', 'solidity', 'ethereum', 'nft', SHOWCASE_TAG],
    date: '14-15 มิถุนายน 2568',
    location: 'Digital Hub อาคาร FYI Center ถนนรามคำแหง กรุงเทพฯ',
    price: '฿1200',
    image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&q=80',
    description: 'ดำดิ่งสู่โลก Blockchain และ Web3 เทคโนโลยีที่กำลังเปลี่ยนโลก เรียนรู้หลักการทำงานของ Blockchain, Smart Contract ด้วยภาษา Solidity บน Ethereum, DeFi (Decentralized Finance), NFT มาตรฐาน ERC-721 และ ERC-1155, การพัฒนา DApp (Decentralized Application) ด้วย Hardhat, Ethers.js และ React, Wallet Integration ด้วย MetaMask เหมาะสำหรับ Developer ที่อยากก้าวสู่ Web3 Industry',
    deadline: '10 มิถุนายน 2568',
    registrationDeadline: future(70),
    participantCount: 20,
    capacity: 20,
    enrolled: 14,
    fee: 1200,
    activityFormat: 'Workshop',
    qualifications: { level: 'มหาวิทยาลัย', fields: ['วิทยาศาสตร์', 'วิศวกรรมศาสตร์'] },
    additionalInfo: ['นำโน้ตบุ๊คมาเอง', 'มีพื้นฐาน JavaScript หรือ Python', 'ได้รับ Testnet ETH สำหรับ Workshop'],
    galleryImages: [
      'https://images.unsplash.com/photo-1640340434855-6084b1f4901c?w=800&q=80',
      'https://images.unsplash.com/photo-1621761191319-c6fb62004040?w=800&q=80',
      'https://images.unsplash.com/photo-1622630998477-20aa696ecb05?w=800&q=80',
    ],
    reviews: [
      { id: 'r29', author: 'ตั้ม Web3', rating: 5, comment: 'เข้าใจ Blockchain ในแบบที่ทำงานได้จริง ไม่ใช่แค่ทฤษฎีครับ Deploy Smart Contract ได้จริงๆ', date: '2025-05-20' },
      { id: 'r30', author: 'เฟิร์น DeFi', rating: 4, comment: 'สนุกมากค่ะ แต่เนื้อหาลึกมาก ต้องมีพื้นฐาน JavaScript มาก่อนจึงจะตามทัน', date: '2025-05-21' },
      { id: 'r31', author: 'พีท Crypto', rating: 5, comment: 'วิทยากร Active ใน Web3 Community จริงๆ ได้ connection กับ Community ดีมากด้วย', date: '2025-05-22' },
    ],
    avgRating: 4.7,
    ratingBreakdown: { '5': 2, '4': 1 },
    organizerName: 'Thai Blockchain Association',
    organizerEmail: 'info@thaiblockchain.org',
    requiresPortfolio: false,
    featured: false,
    views: 189,
    slug: 'blockchain-web3-showcase',
    organizers: [],
  },
  {
    name: 'IoT & Embedded Systems',
    category: 'Hardware',
    tags: ['iot', 'arduino', 'raspberry-pi', 'embedded', 'hardware', SHOWCASE_TAG],
    date: '21-22 มิถุนายน 2568',
    location: 'ห้องปฏิบัติการ IoT คณะวิศวกรรมศาสตร์ มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี (KMUTT)',
    price: '฿850',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80',
    description: 'เรียนรู้การพัฒนาระบบ Internet of Things ด้วย Arduino, Raspberry Pi และ ESP32 ครอบคลุม Sensor Integration, Actuator Control, MQTT Protocol, HTTP REST API สำหรับ IoT, การเชื่อมต่อ Cloud Platform ด้วย AWS IoT Core และ Google Cloud IoT, Dashboard สำหรับ Monitoring ด้วย Grafana และโปรเจกต์ Smart Home ในชีวิตจริง ผู้เข้าร่วมได้ทดลองต่อวงจรจริงพร้อมชุด Hardware ที่จัดเตรียมให้',
    deadline: '17 มิถุนายน 2568',
    registrationDeadline: future(75),
    participantCount: 20,
    capacity: 20,
    enrolled: 16,
    fee: 850,
    activityFormat: 'Workshop',
    qualifications: { level: 'มัธยมปลาย', fields: ['วิทยาศาสตร์', 'คณิตศาสตร์'] },
    additionalInfo: ['จัดเตรียม Hardware ให้ทุกคน', 'นำ Laptop มาเองสำหรับ Programming', 'มีของว่างและเครื่องดื่มตลอดวัน'],
    galleryImages: [
      'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80',
      'https://images.unsplash.com/photo-1561736778-92e52a7769ef?w=800&q=80',
      'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&q=80',
    ],
    reviews: [
      { id: 'r32', author: 'อาร์ม Hardware', rating: 5, comment: 'ต่อวงจรจริงๆ ได้เลยครับ ไม่ใช่แค่ Simulator ของที่ทำได้เอากลับไปบ้านได้ด้วย', date: '2025-06-01' },
      { id: 'r33', author: 'กุ๊กไก่ IoT', rating: 5, comment: 'สร้าง Smart Home เล็กๆ ได้เองเลยค่ะ ประทับใจมาก ไม่คิดว่าจะทำได้', date: '2025-06-02' },
      { id: 'r34', author: 'บาส Embedded', rating: 4, comment: 'น่าสนใจมากครับ แต่อยากให้มีการสอน PCB Design เพิ่มในครั้งต่อไป', date: '2025-06-03' },
      { id: 'r35', author: 'นุ่น Maker', rating: 5, comment: 'วิทยากรมีประสบการณ์จาก Industry จริงๆ ได้เรียนรู้ทั้ง Software และ Hardware อย่างครบถ้วน', date: '2025-06-04' },
    ],
    avgRating: 4.8,
    ratingBreakdown: { '5': 3, '4': 1 },
    organizerName: 'NECTEC สวทช.',
    organizerEmail: 'training@nectec.or.th',
    requiresPortfolio: false,
    featured: false,
    views: 167,
    slug: 'iot-embedded-showcase',
    organizers: [],
  },
  {
    name: 'Machine Learning with Python',
    category: 'Data Science',
    tags: ['machine-learning', 'python', 'tensorflow', 'deep-learning', 'ai', SHOWCASE_TAG],
    date: '5-6 กรกฎาคม 2568',
    location: 'AI Research Center คณะวิทยาการคอมพิวเตอร์ มหาวิทยาลัยสงขลานครินทร์ (มอ.)',
    price: '฿900',
    image: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80',
    description: 'เจาะลึก Machine Learning และ Deep Learning ด้วย Python, TensorFlow 2.x และ Keras ครอบคลุม Supervised Learning, Unsupervised Learning, Neural Networks, Convolutional Neural Network (CNN), Recurrent Neural Network (RNN), Transfer Learning, Model Optimization, Cross-validation และ Hyperparameter Tuning พร้อม Mini Project จำแนกภาพและวิเคราะห์ข้อความด้วย NLP เหมาะสำหรับผู้ที่อยากเป็น ML Engineer หรือ AI Researcher',
    deadline: '1 กรกฎาคม 2568',
    registrationDeadline: future(80),
    participantCount: 25,
    capacity: 25,
    enrolled: 19,
    fee: 900,
    activityFormat: 'Workshop',
    qualifications: { level: 'มหาวิทยาลัย', fields: ['วิทยาศาสตร์', 'วิศวกรรมศาสตร์', 'คณิตศาสตร์'] },
    additionalInfo: ['นำโน้ตบุ๊คมาเอง (GPU แนะนำ หรือใช้ Google Colab)', 'มีพื้นฐาน Python และ คณิตศาสตร์', 'ต้องส่ง Portfolio 1 ชิ้นก่อนเข้าร่วม'],
    galleryImages: [
      'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80',
      'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&q=80',
      'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&q=80',
    ],
    reviews: [
      { id: 'r36', author: 'ฝน AI', rating: 5, comment: 'ลึกมากครับ เนื้อหาระดับมหาวิทยาลัยแต่อธิบายเข้าใจง่าย Train Model ได้จริงๆ ด้วย Google Colab', date: '2025-06-15' },
      { id: 'r37', author: 'นัท Deep', rating: 4, comment: 'ดีมากค่ะ CNN Section น่าสนใจที่สุด แต่อยากให้มีการสอน Deployment เพิ่ม', date: '2025-06-16' },
      { id: 'r38', author: 'วิน ML', rating: 5, comment: 'Portfolio ที่ได้จากค่ายนี้ช่วยให้ผ่านสัมภาษณ์งาน AI ได้เลยครับ', date: '2025-06-17' },
    ],
    avgRating: 4.7,
    ratingBreakdown: { '5': 2, '4': 1 },
    organizerName: 'AI Research Institute Thailand (ARIT)',
    organizerEmail: 'research@airesearch.th',
    requiresPortfolio: true,
    featured: true,
    views: 278,
    slug: 'machine-learning-python-showcase',
    organizers: [],
  },
  {
    name: 'Database Design & SQL',
    category: 'Database',
    tags: ['database', 'sql', 'postgresql', 'database-design', 'backend', SHOWCASE_TAG],
    date: '12-13 กรกฎาคม 2568',
    location: 'ห้องปฏิบัติการ Database มหาวิทยาลัยธรรมศาสตร์ ศูนย์รังสิต ปทุมธานี',
    price: '฿550',
    image: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=800&q=80',
    description: 'เรียนรู้การออกแบบและจัดการฐานข้อมูลอย่างมืออาชีพ ตั้งแต่ Entity-Relationship Diagram (ERD), Normalization (1NF, 2NF, 3NF, BCNF), SQL Advanced Query ด้วย PostgreSQL, Index Optimization, Stored Procedure, Trigger, Transaction Management, Concurrency Control ไปจนถึงหลักการ NoSQL เบื้องต้น เนื้อหาครอบคลุมทั้งทฤษฎีและการลงมือทำโจทย์จริงจากปัญหาที่พบใน Industry',
    deadline: '8 กรกฎาคม 2568',
    registrationDeadline: future(85),
    participantCount: 35,
    capacity: 35,
    enrolled: 25,
    fee: 550,
    activityFormat: 'Workshop',
    qualifications: { level: 'มัธยมปลาย', fields: ['วิทยาศาสตร์', 'คณิตศาสตร์'] },
    additionalInfo: ['นำโน้ตบุ๊คมาเอง', 'ติดตั้ง PostgreSQL และ DBeaver ก่อนมา', 'มีโจทย์ practice ให้ทำต่อที่บ้าน'],
    galleryImages: [
      'https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=800&q=80',
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
      'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80',
    ],
    reviews: [
      { id: 'r39', author: 'ปุ๊ก Database', rating: 5, comment: 'เข้าใจ Normalization แบบที่ไม่เคยเข้าใจมาก่อนเลยค่ะ วิทยากรสอนด้วยตัวอย่างจริงๆ', date: '2025-07-01' },
      { id: 'r40', author: 'โบ้ SQL', rating: 5, comment: 'Index Optimization ที่เรียนนำไปปรับ Query ในงานได้ช้าลงจาก 3 วิ เหลือ 0.1 วิครับ', date: '2025-07-02' },
      { id: 'r41', author: 'เบส Backend', rating: 4, comment: 'ดีมากครับ เนื้อหาครบ แต่อยากให้สอน MongoDB เพิ่มเพื่อเปรียบเทียบ', date: '2025-07-03' },
      { id: 'r42', author: 'มิ้น DBA', rating: 5, comment: 'เรียนแล้วไปสอบ Oracle Certified Associate ได้เลยค่ะ เนื้อหาแน่นมากๆ', date: '2025-07-04' },
    ],
    avgRating: 4.8,
    ratingBreakdown: { '5': 3, '4': 1 },
    organizerName: 'สมาคมผู้บริหารงานไอทีไทย (ATCI)',
    organizerEmail: 'training@atci.or.th',
    requiresPortfolio: false,
    featured: false,
    views: 134,
    slug: 'database-sql-showcase',
    organizers: [],
  },
  {
    name: 'Network Engineering',
    category: 'Infrastructure',
    tags: ['network', 'cisco', 'networking', 'ccna', 'infrastructure', SHOWCASE_TAG],
    date: '19-20 กรกฎาคม 2568',
    location: 'ศูนย์ฝึกอบรม CISCO Academy มหาวิทยาลัยเทคโนโลยีราชมงคล กรุงเทพฯ',
    price: '฿700',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80',
    description: 'เตรียมความพร้อมสู่โลกของ Network Engineering ด้วยหลักสูตรที่ครอบคลุม OSI Model เชิงลึก, TCP/IP Protocol Suite, Routing Protocol (OSPF, EIGRP, BGP), Switching และ VLAN, Network Security ด้วย ACL และ Firewall, VPN, SDN (Software Defined Networking) เบื้องต้น และ Network Troubleshooting อย่างเป็นระบบ ฝึกปฏิบัติบน Cisco Packet Tracer และ GNS3 จำลองเครือข่ายจริง',
    deadline: '15 กรกฎาคม 2568',
    registrationDeadline: future(90),
    participantCount: 25,
    capacity: 25,
    enrolled: 18,
    fee: 700,
    activityFormat: 'Workshop',
    qualifications: { level: 'มัธยมปลาย', fields: ['วิทยาศาสตร์', 'คณิตศาสตร์'] },
    additionalInfo: ['นำโน้ตบุ๊คมาเอง', 'ติดตั้ง Cisco Packet Tracer ก่อนมา', 'มี CCNA Study Guide ให้'],
    galleryImages: [
      'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&q=80',
      'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80',
      'https://images.unsplash.com/photo-1592659762303-90081d34b277?w=800&q=80',
    ],
    reviews: [
      { id: 'r43', author: 'แน็ต Network', rating: 5, comment: 'เตรียมสอบ CCNA ได้ดีมากครับ เนื้อหาตรงกับที่ออกสอบ วิทยากรมีประสบการณ์จริงในสาย Network', date: '2025-07-10' },
      { id: 'r44', author: 'อ้อม Router', rating: 4, comment: 'ดีมากค่ะ Packet Tracer Lab ช่วยให้เข้าใจมากขึ้น แต่อยากได้ลองกับ Hardware จริงบ้าง', date: '2025-07-11' },
      { id: 'r45', author: 'ปั้น Cisco', rating: 5, comment: 'SDN Section ที่สอนทำให้เข้าใจ Future of Networking มากขึ้นมากเลยครับ', date: '2025-07-12' },
    ],
    avgRating: 4.7,
    ratingBreakdown: { '5': 2, '4': 1 },
    organizerName: 'NT National Telecom',
    organizerEmail: 'training@ntplc.co.th',
    requiresPortfolio: false,
    featured: false,
    views: 112,
    slug: 'network-engineering-showcase',
    organizers: [],
  },
  {
    name: 'Digital Marketing & Analytics',
    category: 'Marketing',
    tags: ['digital-marketing', 'seo', 'analytics', 'ads', 'growth', SHOWCASE_TAG],
    date: '26-27 กรกฎาคม 2568',
    location: 'Co-Working Space ชั้น 5 The HIVE Thonglor ทองหล่อ กรุงเทพฯ',
    price: '฿600',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
    description: 'เรียนรู้ Digital Marketing ครบวงจรสำหรับยุค Data-Driven ครอบคลุม SEO (Search Engine Optimization) ทั้ง On-page และ Off-page, Google Ads และ Meta Ads, Content Marketing Strategy, Email Marketing Automation, Social Media Marketing, Google Analytics 4 และ Data Studio, A/B Testing, Conversion Rate Optimization (CRO) และ Growth Hacking Techniques พร้อม Case Study จากแบรนด์ไทยที่ประสบความสำเร็จ เหมาะสำหรับผู้ที่อยากก้าวสู่สาย Digital Marketing',
    deadline: '22 กรกฎาคม 2568',
    registrationDeadline: future(95),
    participantCount: 40,
    capacity: 40,
    enrolled: 32,
    fee: 600,
    activityFormat: 'Workshop',
    qualifications: { level: 'มัธยมปลาย', fields: ['ทุกสาขา'] },
    additionalInfo: ['นำโน้ตบุ๊คมาเอง', 'มี Google Analytics Demo Account ให้ใช้', 'มีอาหารกลางวันและ Coffee Break'],
    galleryImages: [
      'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=800&q=80',
      'https://images.unsplash.com/photo-1533750349088-cd871a92f312?w=800&q=80',
      'https://images.unsplash.com/photo-1553484771-371a605b060b?w=800&q=80',
    ],
    reviews: [
      { id: 'r46', author: 'มิว Marketing', rating: 5, comment: 'ได้ทำ Campaign จริงระหว่างค่ายเลยค่ะ เห็น Result ทันทีว่า Ads ที่ยิงไปได้ผลแค่ไหน ประทับใจมาก', date: '2025-07-15' },
      { id: 'r47', author: 'ต้าร์ Growth', rating: 5, comment: 'Growth Hacking Section เปิดตาสุดๆ ครับ Tactic บางอย่างง่ายมากแต่ได้ผลดีเกินคาด', date: '2025-07-16' },
      { id: 'r48', author: 'เจ SEO', rating: 4, comment: 'SEO ส่วนดีมากค่ะ ได้ทำ Keyword Research จริง แต่อยากให้สอน Technical SEO เพิ่มอีก', date: '2025-07-17' },
      { id: 'r49', author: 'ก้อย Ads', rating: 5, comment: 'คุ้มค่ามากครับ วิทยากรมีประสบการณ์จัดการ Budget Google Ads หลักแสนต่อเดือนมาสอนเอง', date: '2025-07-18' },
    ],
    avgRating: 4.8,
    ratingBreakdown: { '5': 3, '4': 1 },
    organizerName: 'สมาคมโฆษณาดิจิทัล (DAAT)',
    organizerEmail: 'training@daat.in.th',
    requiresPortfolio: false,
    featured: false,
    views: 201,
    slug: 'digital-marketing-showcase',
    organizers: [],
  },
  {
    name: 'Computer Vision with OpenCV',
    category: 'Data Science',
    tags: ['computer-vision', 'opencv', 'python', 'image-processing', 'ai', SHOWCASE_TAG],
    date: '2-3 สิงหาคม 2568',
    location: 'Robotics & Vision Lab คณะวิศวกรรมศาสตร์ สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหาร (สจล.)',
    price: '฿850',
    image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&q=80',
    description: 'เข้าสู่โลกของ Computer Vision ผ่าน OpenCV และ Python สำหรับการประมวลผลภาพและวิดีโอ ครอบคลุม Image Processing Fundamentals, Feature Detection (SIFT, SURF, ORB), Object Detection ด้วย YOLO, Face Recognition ด้วย Deep Face, Optical Flow, Camera Calibration, Augmented Reality เบื้องต้น และโปรเจกต์ Real-time Object Counter ที่ใช้ได้กับกล้อง Webcam จริง เหมาะสำหรับผู้สนใจ AI ด้าน Vision',
    deadline: '29 กรกฎาคม 2568',
    registrationDeadline: future(100),
    participantCount: 20,
    capacity: 20,
    enrolled: 15,
    fee: 850,
    activityFormat: 'Workshop',
    qualifications: { level: 'มหาวิทยาลัย', fields: ['วิทยาศาสตร์', 'วิศวกรรมศาสตร์'] },
    additionalInfo: ['นำโน้ตบุ๊คมาเอง', 'มีพื้นฐาน Python', 'ต้องส่ง Portfolio ก่อนเข้าร่วม', 'มีกล้อง USB สำหรับ Lab'],
    galleryImages: [
      'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80',
      'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&q=80',
      'https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=800&q=80',
    ],
    reviews: [
      { id: 'r50', author: 'วิว Vision', rating: 5, comment: 'YOLO Real-time Detection บน Webcam ตัวเองได้เลยครับ น่าทึ่งมาก ไม่คิดว่าจะทำได้ภายในวันเดียว', date: '2025-07-20' },
      { id: 'r51', author: 'บิ๊ก OpenCV', rating: 5, comment: 'ดีมากค่ะ วิทยากรอธิบาย Math ที่อยู่เบื้องหลังให้เข้าใจได้โดยไม่ต้องจำสูตร', date: '2025-07-21' },
      { id: 'r52', author: 'ออยล์ Image', rating: 4, comment: 'น่าสนใจมากครับ เนื้อหาหนักนิดหน่อยแต่พี่เลี้ยงช่วยดีมาก', date: '2025-07-22' },
      { id: 'r53', author: 'ปลา AR', rating: 5, comment: 'AR Section เป็น Highlight ของค่ายเลยค่ะ ทำ Virtual Object overlay บนกล้องได้สำเร็จ', date: '2025-07-23' },
    ],
    avgRating: 4.8,
    ratingBreakdown: { '5': 3, '4': 1 },
    organizerName: 'VISAI Computer Vision Lab',
    organizerEmail: 'cv-lab@visai.ai',
    requiresPortfolio: true,
    featured: false,
    views: 143,
    slug: 'computer-vision-opencv-showcase',
    organizers: [],
  },
  {
    name: 'AR/VR Development',
    category: 'Game Development',
    tags: ['ar', 'vr', 'unity', 'xr', 'immersive', SHOWCASE_TAG],
    date: '9-10 สิงหาคม 2568',
    location: 'XR Innovation Lab อาคาร Cyberworld สวนอุตสาหกรรมซอฟต์แวร์ ลาดพร้าว กรุงเทพฯ',
    price: '฿1100',
    image: 'https://images.unsplash.com/photo-1592478411213-6153e4ebc07d?w=800&q=80',
    description: 'สัมผัสประสบการณ์การพัฒนา Augmented Reality (AR) และ Virtual Reality (VR) ด้วย Unity XR Toolkit และ OpenXR Standard ครอบคลุม AR Foundation สำหรับ Mobile AR, Marker-based และ Markerless Tracking, Hand Tracking, Spatial Mapping, VR Interaction Design, Comfort Guidelines, Quest 3 Development และ WebXR สำหรับ Browser-based Experience ผู้เข้าร่วมได้ทดลองใช้ Headset จริงและสร้าง XR App ที่นำไปแสดงได้',
    deadline: '5 สิงหาคม 2568',
    registrationDeadline: future(105),
    participantCount: 15,
    capacity: 15,
    enrolled: 11,
    fee: 1100,
    activityFormat: 'Workshop',
    qualifications: { level: 'มัธยมปลาย', fields: ['ทุกสาขา'] },
    additionalInfo: ['นำโน้ตบุ๊คมาเอง (GPU แนะนำ)', 'ติดตั้ง Unity 2022 LTS', 'มี Meta Quest 3 ให้ทดลอง 2 เครื่อง'],
    galleryImages: [
      'https://images.unsplash.com/photo-1617802690992-15d93263d3a9?w=800&q=80',
      'https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac?w=800&q=80',
      'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=800&q=80',
    ],
    reviews: [
      { id: 'r54', author: 'ท็อป XR', rating: 5, comment: 'ลอง Quest 3 ครั้งแรกในชีวิตแล้วได้สร้าง App สำหรับมันด้วยเลยครับ ประสบการณ์สุดยอดมาก', date: '2025-08-01' },
      { id: 'r55', author: 'แนน Immersive', rating: 5, comment: 'AR บน iPhone ที่ทำได้นำไป Demo ในชั้นเรียนได้เลยค่ะ เพื่อนๆ ตื่นตาตื่นใจมาก', date: '2025-08-02' },
      { id: 'r56', author: 'เอิร์ธ Virtual', rating: 4, comment: 'สุดยอดครับ แต่เนื้อหาค่อนข้างลึก ต้องมีพื้นฐาน Unity มาบ้างถึงจะตามทัน', date: '2025-08-03' },
    ],
    avgRating: 4.7,
    ratingBreakdown: { '5': 2, '4': 1 },
    organizerName: 'Meta Developer Circles Thailand',
    organizerEmail: 'thailand@meta.com',
    requiresPortfolio: false,
    featured: false,
    views: 198,
    slug: 'ar-vr-development-showcase',
    organizers: [],
  },
  {
    name: 'Competitive Programming',
    category: 'Programming',
    tags: ['competitive-programming', 'algorithm', 'data-structure', 'problem-solving', SHOWCASE_TAG],
    date: '16-17 สิงหาคม 2568',
    location: 'ห้องแข่งขันโปรแกรมมิ่ง คณะวิทยาการคอมพิวเตอร์ มหาวิทยาลัยเชียงใหม่',
    price: '฿500',
    image: 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=800&q=80',
    description: 'ฝึกฝนทักษะการแก้ปัญหาเชิงอัลกอริทึมสำหรับการแข่งขัน Competitive Programming ระดับประเทศและนานาชาติ ครอบคลุม Data Structures ขั้นสูง (Segment Tree, Fenwick Tree, Trie), Graph Algorithms (Dijkstra, Floyd-Warshall, Bellman-Ford, MST), Dynamic Programming, Greedy Algorithm, Divide and Conquer, String Algorithm (KMP, Z-Algorithm, Suffix Array) และ Computational Geometry เหมาะสำหรับผู้ที่เตรียมแข่ง ICPC, IOI หรือ Codeforces',
    deadline: '12 สิงหาคม 2568',
    registrationDeadline: future(110),
    participantCount: 30,
    capacity: 30,
    enrolled: 22,
    fee: 500,
    activityFormat: 'Workshop',
    qualifications: { level: 'มัธยมปลาย', fields: ['วิทยาศาสตร์', 'คณิตศาสตร์'] },
    additionalInfo: ['นำโน้ตบุ๊คมาเอง', 'มีพื้นฐาน C++ หรือ Python', 'มีโจทย์ให้ฝึกหลังค่าย 100 ข้อ'],
    galleryImages: [
      'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&q=80',
      'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=800&q=80',
      'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&q=80',
    ],
    reviews: [
      { id: 'r57', author: 'โอม Algorithm', rating: 5, comment: 'วิทยากรเป็น ICPC Finalist มาสอนเอง เนื้อหาลึกมากแต่อธิบายได้ชัดเจน เทคนิคที่ได้ใช้แก้โจทย์ได้จริง', date: '2025-08-10' },
      { id: 'r58', author: 'ทิ่น DP', rating: 5, comment: 'DP Section ที่สอนทำให้เข้าใจมากขึ้นกว่าที่เคยอ่านเองเป็นเดือนๆ ครับ ขอบคุณมากครับ', date: '2025-08-11' },
      { id: 'r59', author: 'แอม Graph', rating: 4, comment: 'Graph Algorithm ครบมากค่ะ แต่อยากให้มีการ Practice Contest จำลองด้วยในค่าย', date: '2025-08-12' },
      { id: 'r60', author: 'วาย Codeforces', rating: 5, comment: 'Rating ใน Codeforces ขึ้นจาก 800 เป็น 1400 หลังจากเอาความรู้จากค่ายนี้ไปฝึกครับ', date: '2025-08-13' },
    ],
    avgRating: 4.8,
    ratingBreakdown: { '5': 3, '4': 1 },
    organizerName: 'สมาคมคอมพิวเตอร์โอลิมปิก (IPST)',
    organizerEmail: 'programming@ipst.ac.th',
    requiresPortfolio: false,
    featured: false,
    views: 167,
    slug: 'competitive-programming-showcase',
    organizers: [],
  },
  {
    name: 'Open Source Contribution',
    category: 'Programming',
    tags: ['open-source', 'git', 'github', 'collaboration', 'community', SHOWCASE_TAG],
    date: '23-24 สิงหาคม 2568',
    location: 'Hubba-TO Ekkamai สุขุมวิท 63 กรุงเทพฯ',
    price: '฿400',
    image: 'https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=800&q=80',
    description: 'เรียนรู้วิธีการมีส่วนร่วมในโปรเจกต์ Open Source ตั้งแต่ Git Workflow ขั้นสูง (Rebase, Cherry-pick, Bisect), GitHub Flow, Fork และ Pull Request, Code Review Best Practices, Semantic Versioning, Changelog Management, การเขียน Good Commit Message, GitHub Actions สำหรับ CI/CD, Contribution Guidelines และ Community Etiquette ผู้เข้าร่วมจะได้ Merge Pull Request แรกใน Open Source Project จริงภายในค่าย',
    deadline: '19 สิงหาคม 2568',
    registrationDeadline: future(115),
    participantCount: 30,
    capacity: 30,
    enrolled: 20,
    fee: 400,
    activityFormat: 'Workshop',
    qualifications: { level: 'มัธยมปลาย', fields: ['ทุกสาขา'] },
    additionalInfo: ['นำโน้ตบุ๊คมาเอง', 'มีบัญชี GitHub แล้ว', 'มีพื้นฐาน Programming ภาษาใดก็ได้'],
    galleryImages: [
      'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&q=80',
      'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&q=80',
      'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&q=80',
    ],
    reviews: [
      { id: 'r61', author: 'กิ๊ก GitHub', rating: 5, comment: 'Merge PR แรกของชีวิตได้ในค่ายนี้เลยครับ ดีใจมากที่ได้มีส่วนช่วย Open Source Community', date: '2025-08-20' },
      { id: 'r62', author: 'ลีน Git', rating: 5, comment: 'Git Rebase และ Cherry-pick ที่สอนช่วยแก้ปัญหาที่เคย Confuse มาตลอดได้ค่ะ', date: '2025-08-21' },
      { id: 'r63', author: 'พล Contributor', rating: 5, comment: 'Community ดีมากครับ ได้เพื่อนที่ตอนนี้ Collaborate โปรเจกต์ด้วยกันอยู่', date: '2025-08-22' },
    ],
    avgRating: 5.0,
    ratingBreakdown: { '5': 3 },
    organizerName: 'GitHub Education Thailand',
    organizerEmail: 'education-th@github.com',
    requiresPortfolio: false,
    featured: false,
    views: 121,
    slug: 'open-source-showcase',
    organizers: [],
  },
  {
    name: 'System Design & Architecture',
    category: 'Programming',
    tags: ['system-design', 'architecture', 'scalability', 'microservices', 'backend', SHOWCASE_TAG],
    date: '30-31 สิงหาคม 2568',
    location: 'บริษัท Agoda Technology สาทร กรุงเทพฯ (เยี่ยมชม) + ห้องประชุม Online',
    price: '฿1500',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
    description: 'ค่าย System Design สำหรับผู้ที่ต้องการยกระดับสู่ Senior Engineer เรียนรู้การออกแบบระบบที่รองรับ Scale ได้ ครอบคลุม CAP Theorem, Consistent Hashing, Load Balancing, Caching Strategy (CDN, Redis, Memcached), Message Queue (Kafka, RabbitMQ), Microservices vs Monolith, API Gateway, Service Mesh, Database Sharding, Event-driven Architecture และ การออกแบบระบบชื่อดังอย่าง URL Shortener, Twitter Feed, YouTube, WhatsApp ผ่าน Mock Interview',
    deadline: '26 สิงหาคม 2568',
    registrationDeadline: future(120),
    participantCount: 15,
    capacity: 15,
    enrolled: 10,
    fee: 1500,
    activityFormat: 'Workshop',
    qualifications: { level: 'มหาวิทยาลัย', fields: ['วิทยาศาสตร์', 'วิศวกรรมศาสตร์'] },
    additionalInfo: ['ต้องส่ง Resume และ Portfolio ก่อนเข้าร่วม', 'มีประสบการณ์ทำงาน/project ด้าน software อย่างน้อย 1 ปี', 'มีอาหารกลางวันและ Networking Dinner'],
    galleryImages: [
      'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800&q=80',
      'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80',
      'https://images.unsplash.com/photo-1543269865-cbf427effbad?w=800&q=80',
    ],
    reviews: [
      { id: 'r64', author: 'แม็กซ์ Senior', rating: 5, comment: 'คุ้มมากสำหรับ Price ครับ System Design Interview Mock ที่ทำในค่ายนี้ช่วยให้ผ่าน Interview ที่ Big Tech ได้', date: '2025-08-25' },
      { id: 'r65', author: 'พร Staff Engineer', rating: 5, comment: 'เนื้อหาลึกมากค่ะ วิทยากรเป็น Principal Engineer จากบริษัทชั้นนำ ได้มุมมองที่ไม่มีใน YouTube', date: '2025-08-26' },
      { id: 'r66', author: 'จิ๊บ Architect', rating: 5, comment: 'Kafka Workshop ทำให้เข้าใจ Event-driven ที่บริษัทใช้อยู่ได้ดีขึ้นมากครับ ขอบคุณมาก', date: '2025-08-27' },
      { id: 'r67', author: 'บี Scale', rating: 4, comment: 'ดีมากครับ แต่อยากให้มีเวลา Hands-on เพิ่ม Lecture เยอะมากจนเนื้อหาล้นนิดหน่อย', date: '2025-08-28' },
    ],
    avgRating: 4.8,
    ratingBreakdown: { '5': 3, '4': 1 },
    organizerName: 'Agoda Technology',
    organizerEmail: 'tech-dev@agoda.com',
    requiresPortfolio: true,
    featured: true,
    views: 389,
    slug: 'system-design-showcase',
    organizers: [],
  },
  {
    name: 'Full Stack Bootcamp',
    category: 'Programming',
    tags: ['fullstack', 'react', 'nodejs', 'nextjs', 'typescript', SHOWCASE_TAG],
    date: '6-8 กันยายน 2568',
    location: 'WeWork อาคาร One City Centre ถนนเพลินจิต กรุงเทพฯ',
    price: '฿1000',
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&q=80',
    description: 'ค่าย Full Stack Bootcamp สุดเข้มข้น 3 วัน ที่จะพาคุณสร้างเว็บแอปพลิเคชันครบถ้วนตั้งแต่ Frontend ถึง Backend ด้วย TypeScript, React 18, Next.js 14 (App Router), Tailwind CSS, Node.js, Express, Prisma ORM, PostgreSQL, NextAuth.js สำหรับ Authentication, AWS S3 สำหรับ File Upload และ Vercel/Railway สำหรับ Deployment โปรเจกต์ที่ได้สามารถนำไป Deploy ให้ผู้ใช้งานได้จริง และนำเข้า Portfolio ได้ทันที',
    deadline: '2 กันยายน 2568',
    registrationDeadline: future(125),
    participantCount: 25,
    capacity: 25,
    enrolled: 20,
    fee: 1000,
    activityFormat: 'Hackathon',
    qualifications: { level: 'มัธยมปลาย', fields: ['วิทยาศาสตร์', 'คณิตศาสตร์'] },
    additionalInfo: ['นำโน้ตบุ๊คมาเอง', 'มีพื้นฐาน JavaScript/HTML/CSS', 'มีอาหารกลางวันและ Snack ตลอด 3 วัน'],
    galleryImages: [
      'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&q=80',
      'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&q=80',
      'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80',
    ],
    reviews: [
      { id: 'r68', author: 'มิน Full Stack', rating: 5, comment: 'Deploy เว็บแอปแรกในชีวิตได้ในค่ายนี้ครับ ตอนนี้ยังใช้งานอยู่จริงๆ เพื่อนเอาไปใช้งานด้วย', date: '2025-09-01' },
      { id: 'r69', author: 'เอ Next.js', rating: 5, comment: 'App Router ของ Next.js ที่สอนทำให้เข้าใจกว่าที่อ่าน Documentation เองเยอะมากค่ะ', date: '2025-09-02' },
      { id: 'r70', author: 'โน TypeScript', rating: 4, comment: 'ดีมากครับ แต่ 3 วันยังน้อยไปสำหรับเนื้อหาที่เยอะ ต้องทบทวนเองอีกหน่อย', date: '2025-09-03' },
      { id: 'r71', author: 'ตุ้ย Deploy', rating: 5, comment: 'Prisma ORM ช่วยให้ทำงานกับ Database ง่ายขึ้นมากเลยครับ Mentor ที่ดูแลตลอดค่ายก็ดีมาก', date: '2025-09-04' },
    ],
    avgRating: 4.8,
    ratingBreakdown: { '5': 3, '4': 1 },
    organizerName: 'LINE Thailand Developer Relations',
    organizerEmail: 'devrel@linecorp.com',
    requiresPortfolio: false,
    featured: true,
    views: 445,
    slug: 'fullstack-bootcamp-showcase',
    organizers: [],
  },
];

// GET — get count of showcase camps
export async function GET() {
  try {
    const col = await getCollection('camps');
    const count = await col.countDocuments({ tags: SHOWCASE_TAG });
    return NextResponse.json({ count, tag: SHOWCASE_TAG });
  } catch {
    return NextResponse.json({ error: 'Failed' }, { status: 500 });
  }
}

// PUT — toggle visibility of showcase camps (status: active | showcase_hidden)
export async function PUT(req: Request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.email || (session.user.role !== 'admin' && session.user.role !== 'super_admin')) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await req.json() as { visible?: boolean };
    const col = await getCollection('camps');
    const newStatus = body.visible ? 'active' : 'showcase_hidden';
    await col.updateMany({ tags: SHOWCASE_TAG }, { $set: { status: newStatus, updatedAt: new Date() } });
    return NextResponse.json({ success: true, status: newStatus });
  } catch {
    return NextResponse.json({ error: 'Failed' }, { status: 500 });
  }
}

// POST action=seed | action=clear
export async function POST(req: Request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.email || (session.user.role !== 'admin' && session.user.role !== 'super_admin')) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await req.json() as { action?: string; visible?: boolean };
    const col = await getCollection('camps');

    if (body.action === 'clear') {
      const result = await col.deleteMany({ tags: SHOWCASE_TAG });
      return NextResponse.json({ success: true, deleted: result.deletedCount });
    }

    if (body.action === 'seed') {
      // Delete existing showcase camps first
      await col.deleteMany({ tags: SHOWCASE_TAG });

      const now = new Date();
      const campStatus = body.visible ? 'active' : 'showcase_hidden';
      const docs = SHOWCASE_CAMPS.map(camp => ({
        ...camp,
        _id: new ObjectId(),
        status: campStatus,
        createdAt: now,
        updatedAt: now,
      }));

      await col.insertMany(docs);
      return NextResponse.json({ success: true, inserted: docs.length });
    }

    return NextResponse.json({ error: 'Invalid action' }, { status: 400 });
  } catch (e) {
    console.error(e);
    return NextResponse.json({ error: 'Failed' }, { status: 500 });
  }
}
